### ISSUE TITLE
Product Details Reducer and Action

### ISSUE THREAD

**Issue by Buenaventura-Celine** [SinangAugust/E-Commerce-Web-Application#16]
Found some minor bugs:
![image](https://user-images.githubusercontent.com/52587198/145602791-55e9bd23-f59f-4565-8b99-2a828fc21229.png)

Error in backend terminal:
TypeError: BaseManager.all() got an unexpected keyword argument '_id'

**Comment by SinangAugust** [comment]
`product = Product.objects.get(_id=pk)`
